CREATE TABLE PREGUNTAS
(
ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
PREGUNTA VARCHAR(250) NOT NULL,
EXPLICACION VARCHAR(250),
RESPUESTA BOOLEAN NOT NULL DEFAULT FALSE
);
SELECT * FROM APP.PREGUNTAS FETCH FIRST 100 ROWS ONLY;

INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('Los almogavares tomaron Atenas','Si, por venganza',true);
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('China es un democracia','No te lo crees ni tu',false);
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('Andorra es un paraiso fiscal', 'No, pertenece al FMI',false);
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('La capital de Islandia es Quebec','La capital de Reikiavik',false);
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('La capital de Islandia es Quebec','La capital de Reikiavik',false)
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('Andorra es un paraiso fiscal', 'No, pertenece al FMI',false)
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('China es un democracia','No te lo crees ni tu',false)
INSERT INTO PREGUNTAS (PREGUNTA, EXPLICACION, RESPUESTA)
VALUES('Los almogavares tomaron Atenas','Si, por venganza',true);


